server.port: 7000
server.error.include-message: always

app:
  user-service:
    host: localhost
    port: 7001
  tempuser-service:
    host: localhost
    port: 7002

logging:
  level:
    root: INFO
